name: Huntingguild
author: Vestri
description: huntingguild
version: 0.18
api-version: 1.15
main: hg.java.HuntingGuild
depend: [PlayertoSql]
permissions:
  hg.hgbuilder:
    description: buildercommands
    default: op
  hg.hgplayer:
    description: player commands
    default: op
commands:
  hgeditgrouplive:
    description: change/get groupe live
    usage: /hgeditgrouplive <huntingroundname> [lives] [leavebydeath]
  hgeditcommands:
    description: add/remove hunting ground commands. Playervariable in Command %player%. Commands without /
    usage: /hgeditcommands <huntingroundname> <win/lose/start> [command] [remove]
  hgcreate:
    description: create a new hunting ground
    usage: /hgcreate <huntingroundname> <world>
  hgowninv:
    description: set player own inventory for huntingground
    usage: /hgowninv <huntingroundname> <true/false>
  hgsetmsp:
    description: add/remove Spawnpoint for Mobs
    usage: /hgsetmsp <huntingroundname> <x> <y> <z> [remove]
  hgsetpsp:
    description: add/remove Spawnpoint for Player
    usage: /hgsetpsp <huntingroundname> <x> <y> <z> [remove]
  hgsetwave:
    description: add/remove wave for Mobs
    usage: /hgsetwave <huntingroundname> <starttimer> <autostart> [remove]
  hgsetwavemo:
    description: add/remove Mobs for wave
    usage: /hgsetwavemo <huntingroundname> <waveid> <spawnpointname> <mobname> <amout> [remove]
  hgcreateg:
    description: add group for hunting ground
    usage: /hgcreateg <huntingroundname> <size>
  hgsave:
    description: save hunting ground
    usage: /hgsave <huntingroundname>
  hgmode:
    description: change the hunting ground mode (live/build)
    usage: /hgmode <huntingroundname>
  hgstartwave:
    description: start wave
    usage: /hgstartwave <huntingroundname>
  hgstart:
    description: start hg
    usage: /hgstart <huntingroundname>
  hgjoin:
    description: join hg
    usage: /hgjoin <huntingroundname>
  hgleave:
    description: leave hg
    usage: /hgleave <huntingroundname>
  hgplready:
    description: set player ready for hg
    usage: /hgplready <huntingroundname>
  hgchangerespawn:
    description: change the player respawnpoint in the hunting ground on runtime (only over console command)
    usage: /hgplready <huntingroundname> <playerspawnpointid>
  dujoin:
    description: join du
    usage: /dujoin <huntingroundname>
  hgstartreadycheck:
    description: start readycheck
    usage: /hgstartreadycheck <huntingroundname>
  hgsetvisits:
    description: set visits per hour
    usage: /hgsetvisits <huntingroundname> <count>
  hgload:
    description: load hg from folder
    usage: /hgload <huntingroundname>
